-- CRIANDO UMA TABLESPACE PERMANENTE PARA O USAR NO NOVO ESQUEMA QUE SERÁ CRIADO
CREATE TABLESPACE tbs_perm_alunobd
DATAFILE 'tbs_perm_alunobd.dat'
SIZE 10M
REUSE
AUTOEXTEND ON NEXT 10M MAXSIZE 200M;

-- CRIANDO UMA TABLESPACE TEMPORARIA PARA O USAR NO NOVO ESQUEMA QUE SERÁ CRIADO
CREATE TEMPORARY TABLESPACE tbs_temp_alunobd
TEMPFILE 'tbs_temp_alunobd.dbf'
SIZE 5M
AUTOEXTEND ON;

-- NAO CRIEI ESTA ABAIXO (NAO COMPREENDI TOTALMENTE)
CREATE UNDO TABLESPACE tbs_undo_alunobd
DATAFILE 'tbs_undo_alunobd.f'
SIZE 5M
AUOEXTEND ON
RETENTION GUARANTEE;

--CRIANDO O NOVO ESQUEMA E USANDO AS TABLESPACES CRIADAS ANTES
CREATE USER alunobd
IDENTIFIED BY alunobd
DEFAULT TABLESPACE tbs_perm_alunobd
TEMPORARY TABLESPACE tbs_temp_alunobd
QUOTA 20M ON tbs_perm_alunobd;

--DANDOS DIREITOS E PREVILEGIOS PARA O USUARIO QUE CRIEI ACIMA
GRANT CREATE SESSION TO alunobd;
GRANT CREATE TABLE TO alunobd;
GRANT CREATE VIEW TO alunobd;
GRANT CREATE ANY TRIGGER TO alunobd;
GRANT CREATE ANY PROCEDURE TO alunobd;
GRANT CREATE SEQUENCE TO alunobd;
GRANT CREATE synonym TO alunobd;

--PARA USAR O QUE FOI CRIADO ACIMA VOCÊ PRECISA AGORA LOGAR NA CONTA CRIADA
--CRIANDO TABELA PRODUTOS

CREATE TABLE PRODUTOS(
COD_PRODUTO NUMERIC,
NOME_PRODUTO VARCHAR(200),
PRECO NUMERIC);

--CRIANDO UMA PRIMARY KEY NA TABELA PRODUTOS
--UMA PRIMARY KEY PODE SER CRIADA USANDO 1, 2, OU MAIS COLUNAS
--DESDE QUE OBEDEÇA AS REGRAS DE PRIMARY KEY

--USAREI ALTER TABLE PARA CRIAR A PK, EXISTEM 2 OUTRAS MANEIRAS...

ALTER TABLE PRODUTOS
ADD CONSTRAINT pk_produtos PRIMARY KEY (cod_produto);

--CRIANDO TABELA EXPORTACAO. E JÁ DEFININDO PK LOGO NA CRIACAO DA TABELA
CREATE TABLE EXPORTACAO(
COD_DEST_EXPORT CHAR(4),
CONSTRAINT pk_exportacao PRIMARY KEY (cod_dest_export),
NOME_DEST_EXPORT VARCHAR(200),
POPULACAO NUMERIC,
CONTINENTE VARCHAR(200)
);

CREATE TABLE vendas(
DATA_VENDA VARCHAR (8),
COD_PRODUTO NUMERIC,
CONSTRAINT FK_PRODUTOS
FOREIGN KEY (COD_PRODUTO)
REFERENCES PRODUTOS(COD_PRODUTO));


--INSERINDO DADOS NA TABELA PRODUTOS
INSERT INTO PRODUTOS 
VALUES(
101, 'MELÃO', 800
);

INSERT INTO PRODUTOS (COD_PRODUTO, NOME_PRODUTO, PRECO)
VALUES 
( 103, 'MAÇÃ', 120);
INSERT INTO PRODUTOS (COD_PRODUTO, NOME_PRODUTO, PRECO)
VALUES
( 104, 'LIMÃO', 200);
INSERT INTO PRODUTOS VALUES
(200, 'CEREJA', 200);
INSERT INTO PRODUTOS VALUES
(202, 'CAQUI', 160);
INSERT INTO PRODUTOS VALUES
(301, 'PESSEGO', 100);
INSERT INTO PRODUTOS VALUES
(302, 'KIWI', 200);
INSERT INTO PRODUTOS VALUES
(421, 'MEXIRICA', 350);
INSERT INTO PRODUTOS VALUES
(422, 'LARANJA', 550);
INSERT INTO PRODUTOS VALUES
(423, 'TANGERINA', 250);
INSERT INTO PRODUTOS VALUES
(112, 'CÔCO', 170);

--VISUALIZAR A TABELA POVOADA
SELECT * FROM PRODUTOS;

-- POVOANDO TABELA DE  EXPORTACAO
INSERT INTO EXPORTACAO VALUES
( 
'PAN', 'PANAMA', 3405813, 'AMERICA'
);

INSERT INTO EXPORTACAO	(cod_dest_export,		nome_dest_export, 	populacao,	continente)
VALUES					('AUS',					'AUSTRALIA',		24385195,	'OCEANIA');

INSERT INTO EXPORTACAO 	(cod_dest_export,		nome_dest_export,	populacao,	continente)
VALUES					('IDN',					'INDONESIA',		251160124,	'OCEANIA');

INSERT INTO EXPORTACAO
VALUES					('LKA',					'SIRI LANKA',		21128773,	'ASIA');

INSERT INTO exportacao	
VALUES					('TR',					'TURQUIA',			75627384,	'EUROPA');

INSERT INTO EXPORTACAO 	
VALUES 					('RS',					'SERVIA',			10147398,	'EUROPA');				

--EXIBINDO TABELA DE EXPORTACAO
SELECT * FROM EXPORTACAO;

--EXIBINDO TABELA DE EXPORTACAO ONDE for EUROPA
SELECT * FROM EXPORTACAO  
WHERE CONTINENTE LIKE 'EUROPA';

--EXIBINDO TABELA DE EXPORTACAO ONDE POPULACAO FOR MENOR QUE 12MI
SELECT * FROM ALUNOBD.EXPORTACAO
WHERE POPULACAO < 12000000;

--EXIBINDO TABELA DE VENDAS
SELECT * FROM VENDAS;

--FALTOU COLUNA DE QUANTIDADE, VAMOS INSERIR A COLUNA
ALTER TABLE VENDAS
ADD QUANTIDADE INTEGER;

--EXIBIR TABELA VENDAS PARA CONFERIR INCLUSAO DA COLUNA QUANTIDADE
SELECT * FROM VENDAS;

--POVOAR TABELA VENDAS COM DADOS
INSERT INTO VENDAS VALUES (
'02/07', 102, 1500);
INSERT INTO VENDAS VALUES (
'02/07', 101, 1500);
INSERT INTO VENDAS VALUES (
'05/11', 103, 1700);
INSERT INTO VENDAS VALUES (
'8/11', 101, 500);
INSERT INTO VENDAS VALUES (
'8/11', 104, 500);
INSERT INTO VENDAS VALUES (
'19/05', 202, 100);

--TENTE INSERIR NA TABELA VENDAS
--UM CODIGO DE PRODUTO QUE NAO EXISTA
--DENTRO DA TABELA PRODUTOS... 
INSERT INTO VENDAS VALUES (
'03/08', 999, 100);

--CASO VOCE INSIRA UM PRODUTO QUE EXISTA MAS
--TENHA ERRADO NA QUANTIDADE OU NA DATA, CONSERTE
INSERT INTO VENDAS VALUES (
'01/01', 301, 12000);

DELETE FROM VENDAS
WHERE DATA_VENDA = '01/01';

--FAZER UMA SELECAO POR NOME DO PRODUTO RANQUEANDO POR PRECO
SELECT * FROM PRODUTOS
WHERE NOME_PRODUTO LIKE '%ÃO'
ORDER BY PRECO; 

--OBTENDO MEDIA DE VALORES DE CADA LINHA DA TABELA PRODUTOS
SELECT AVG(PRECO)
FROM PRODUTOS;

--OBTER NUMERO DE LINHAS DA TABELA PRODUTOS
SELECT COUNT (PRECO)
FROM (PRODUTOS);

--SOMA DOS VALORES DE TODAS AS TABELAS
SELECT SUM (PRECO)
FROM (PRODUTOS);

--EXIBE O NUMERO DE ITEM QUE SAO DIFERENTES NA COLUNA COD_PRODUTO
--DENTRO DA TABELA VENDAS
SELECT COUNT (DISTINCT COD_PRODUTO)
FROM VENDAS;


--GERAR RELATORIO DE VENDAS CASANDO PLANILHA DE VENDAS COM A DE PRODUTOS.

SELECT VENDAS.DATA_VENDA, VENDAS.COD_PRODUTO, VENDAS.QUANTIDADE, 
PRODUTOS.NOME_PRODUTO, PRODUTOS.PRECO

FROM VENDAS, PRODUTOS

WHERE VENDAS.COD_PRODUTO = PRODUTOS.COD_PRODUTO;

--VEJA QUE NA TABELA DE VENDAS NAO COLOQUEI O CODIGO DE DESTINO
--PARA ONDE VAO OS PRODUTOS COMPRADOS. ESSE CODIGO TEM QUE SER
--INFORMADO E POSSO OBTE-LO NA TABELA EXPORTACAO

/*CASO VOCE QUEIRA INSERIR UMA COLUNA NUMA
E CRIAR UMA PK, SIGA O MODELO ABAIXO
CREATE TABLE teste1
(id NUMBER(4) NOT NULL,
CONSTRAINT pk_teste1 PRIMARY KEY (id));

CREATE TABLE teste2
(nome varchar2(10)
);

ALTER TABLE TESTE2
ADD id NUMBER(4);

ALTER TABLE teste2
ADD CONSTRAINT fk_teste1
FOREIGN KEY (id)
REFERENCES TESTE1(ID);

SELECT * FROM teste2;
*/

-- INSERÇÃO: INSERIR PRODUTOS NUMA TABELA

SELECT * FROM EXPORTACAO;

INSERT INTO EXPORTACAO (COD_DEST_EXPORT, NOME_DEST_EXPORT, POPULACAO, CONTINENTE) 
VALUES ('BRA', 'BRASIL', 9, 'AMERICA');

--ATUALIZAR: ATUALIZAR DADOS EM UMA TABELA
SELECT * FROM EXPORTACAO;

UPDATE EXPORTACAO
SET POPULACAO=210277823
WHERE POPULACAO='9';

--APAGAR LINHA/TUPLA INTEIRA
SELECT * FROM EXPORTACAO;

DELETE FROM EXPORTACAO
WHERE COD_DEST_EXPORT = 'BRA';

--CRIAR UMA VIEW DE PRODUTOS MAIS COMPRADOS DA TABELA PRODUTOS
CREATE VIEW PRODUTOS_MAIS_CAROS
AS SELECT COD_PRODUTO, QUANTIDADE 
FROM VENDAS
WHERE QUANTIDADE >= 1000;

--MOSTRAR A 'VIEW' CRIADA
SELECT * FROM PRODUTOS_MAIS_CAROS;

--UMA VIEW PODE SER ATUALIZADA OU APAGADA.
--NAO MOSTRAREI ISSO AGORA.

